// ВСТАВЬТЕ СЮДА ДВА ЗНАЧЕНИЯ ИЗ SUPABASE: URL и anon public key
const SUPABASE_URL = 'sb_publishable_SuIQ5ub3SSUQ2RfMgq-Tlw_WwsE78Pe';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrYXptZnFzbm9vaGFqcGt5bG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAyNjE2ODcsImV4cCI6MjEwNTgzNzY4N30.49Akjm84KAwAoFpKY1_KXQo2sDjGk20Jimjy3oNyCpQ';
const db = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

let currentClass = null;
let students = [];
const $ = id => document.getElementById(id);
const today = new Date().toISOString().slice(0,10);
$('dateInput').value = today;

function toast(msg){$('toast').textContent=msg;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
async function loadClasses(){const {data,error}=await db.from('classes').select('*').order('name');if(error)return toast(error.message);$('classes').innerHTML='';for(const c of data){const div=document.createElement('div');div.className='class-item';div.innerHTML=`<button class="openClass">${escapeHtml(c.name)}</button><button class="delete">×</button>`;div.querySelector('.openClass').onclick=()=>openClass(c);div.querySelector('.delete').onclick=async()=>{if(confirm('Удалить класс и всех его учеников?')){await db.from('classes').delete().eq('id',c.id);if(currentClass?.id===c.id){currentClass=null;$('workspace').classList.add('hidden')}loadClasses()}};$('classes').appendChild(div)}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function openClass(c){currentClass=c;$('workspace').classList.remove('hidden');$('classTitle').textContent=c.name;await loadStudents();await renderAttendance();}
async function loadStudents(){const {data,error}=await db.from('students').select('*').eq('class_id',currentClass.id).order('name');if(error)return toast(error.message);students=data;$('studentCount').textContent=`Учеников: ${data.length}`}
async function renderAttendance(){const date=$('dateInput').value;const ids=students.map(s=>s.id);let records=[];if(ids.length){const r=await db.from('attendance').select('*').in('student_id',ids).eq('attendance_date',date);if(r.error)return toast(r.error.message);records=r.data}const map=new Map(records.map(x=>[x.student_id,x]));$('attendanceBody').innerHTML='';students.forEach((s,i)=>{const a=map.get(s.id)||{status:'present',reason:''};const tr=document.createElement('tr');tr.innerHTML=`<td>${i+1}</td><td>${escapeHtml(s.name)}</td><td><div class="status"><button data-s="present">Был</button><button data-s="late">Опоздал</button><button data-s="absent">Не был</button></div></td><td><input class="reason" placeholder="Причина (если отсутствовал)" value="${escapeHtml(a.reason||'')}"></td><td><button class="delete secondary">Удалить</button></td>`;tr.querySelectorAll('.status button').forEach(b=>{if(b.dataset.s===a.status)b.classList.add('selected');b.onclick=()=>saveAttendance(s.id,b.dataset.s,tr)});tr.querySelector('.reason').onchange=()=>saveAttendance(s.id,a.status,tr);tr.querySelector('.delete').onclick=()=>deleteStudent(s.id);$('attendanceBody').appendChild(tr)})}
async function saveAttendance(studentId,status,tr){const reason=tr.querySelector('.reason').value;const {error}=await db.from('attendance').upsert({student_id:studentId,attendance_date:$('dateInput').value,status,reason:status==='absent'?reason:null},{onConflict:'student_id,attendance_date'});if(error)toast(error.message);else{tr.querySelectorAll('.status button').forEach(b=>b.classList.toggle('selected',b.dataset.s===status));toast('Сохранено')}}
async function deleteStudent(id){if(!confirm('Удалить ученика?'))return;await db.from('students').delete().eq('id',id);await loadStudents();await renderAttendance()}
async function renderStats(){const ids=students.map(s=>s.id);$('statsBody').innerHTML='';if(!ids.length)return;const {data,error}=await db.from('attendance').select('*').in('student_id',ids);if(error)return toast(error.message);const by=new Map();for(const s of students)by.set(s.id,{p:0,l:0,a:0});for(const r of data){const x=by.get(r.student_id);if(x)x[r.status==='present'?'p':r.status==='late'?'l':'a']++}students.forEach(s=>{const x=by.get(s.id), total=x.p+x.l+x.a, pct=total?Math.round(((x.p+x.l)/total)*100):0;const tr=document.createElement('tr');tr.innerHTML=`<td>${escapeHtml(s.name)}</td><td>${total}</td><td>${x.p}</td><td>${x.l}</td><td>${x.a}</td><td><b>${pct}%</b></td>`;$('statsBody').appendChild(tr)})}
$('addClassBtn').onclick=()=>{$('className').value='';$('classDialog').showModal()};$('saveClassBtn').onclick=async e=>{e.preventDefault();const name=$('className').value.trim();if(!name)return;const {error}=await db.from('classes').insert({name});if(error)toast(error.message);else{$('classDialog').close();loadClasses()}};
$('addStudentBtn').onclick=()=>{$('studentName').value='';$('studentDialog').showModal()};$('saveStudentBtn').onclick=async e=>{e.preventDefault();const name=$('studentName').value.trim();if(!name||!currentClass)return;const {error}=await db.from('students').insert({class_id:currentClass.id,name});if(error)toast(error.message);else{$('studentDialog').close();await loadStudents();await renderAttendance()}};
$('dateInput').onchange=renderAttendance;$('printBtn').onclick=()=>window.print();document.querySelectorAll('.tab').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const stats=b.dataset.tab==='stats';$('attendanceTab').classList.toggle('hidden',stats);$('statsTab').classList.toggle('hidden',!stats);if(stats)await renderStats()});
loadClasses();
