create table if not exists classes (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists students (
  id bigint generated by default as identity primary key,
  class_id bigint not null references classes(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  student_id bigint not null references students(id) on delete cascade,
  attendance_date date not null,
  status text not null check (status in ('present','late','absent')),
  reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(student_id, attendance_date)
);

alter table classes enable row level security;
alter table students enable row level security;
alter table attendance enable row level security;

drop policy if exists "public classes" on classes;
drop policy if exists "public students" on students;
drop policy if exists "public attendance" on attendance;

create policy "public classes" on classes for all to anon using (true) with check (true);
create policy "public students" on students for all to anon using (true) with check (true);
create policy "public attendance" on attendance for all to anon using (true) with check (true);
